AWSTemplateFormatVersion: '2010-09-09'
Description: Simple LAMP Stack on EC2

Resources:
  LAMPInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.small
      ImageId: ami-12345678 # Replace with your preferred Amazon Linux AMI ID
      KeyName: your-key-pair # Replace with your key pair
      SecurityGroupIds:
        - !Ref LampSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd mariadb-server php php-mysqlnd
          systemctl start httpd
          systemctl enable httpd
          systemctl start mariadb
          systemctl enable mariadb

  LampSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Adjust this for better security
